version: '1.1'

services:
  eureka-sv:
    build: eureka-sv
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - productscartssales-network
  products-service:
    build: products-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - productscartssales-network
  shoppingcart-service:
    build: shoppingcart-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - productscartssales-network
  sales-service:
    build: sales-service
    mem_limit: 512m
    ports:
      - "8084:8084"
    networks:
      - productscartssales-network
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - productscartssales-network
  config-server:
    build: config-server
    mem_limit: 512m
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-sv:8761/eureka
    networks:
      - productscartssales-network
networks:
  productscartssales-network: