server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    confing:
      git:
        uri: https://github.com/leanmza/Proyecto-final-Microservicios.git
        searchPaths: config-data
        username: ${GIT_USER}
        password: ${GIT_PASSWORD}